@startuml
title on Sensor Join
autonumber
'Entity
participant Sensor as sensor <<New Face>>
participant Leader as leader <<extend Sensor>>
participant Server as backend <<LoRaWAN Backend>> #c9c9ff
'Sequence
sensor -> sensor: scan surrounding node on BLE
alt Node Is Exist
    autonumber 2
    sensor -> sensor: join a scanned group
    sensor -> backend: join lorawan network
    sensor -> backend: notify I joined group
else Node Is Not Exist
    autonumber 2
    sensor -> backend: join lorawan network
    sensor -> backend: send sensor data
    sensor -> sensor: sleep lorawan and advertise "I'm not in any group" on BLE
    alt Leader Scan This Node
        activate leader
            leader -> sensor: scan advertise node
            leader -> backend: notify node not joining
            backend -> backend: register node not joining to leader group
            sensor -> backend: send sensor data
            backend -> sensor: notify group you join next
        deactivate leader
    else Leader Can't Scan This Node
        sensor -> sensor: retry from step 2 on Node Is Not Exist
    end
end
@enduml