@startuml
title on Sensor Leave
autonumber
'Entity
participant Member as member <<extend Sensor>>
participant Leader as leader <<extend Sensor>>
participant Server as backend <<LoRaWAN Backend>> #c9c9ff
'Sequence
member -> member: out of order by dead battery
loop
leader -> member: scan on BLE
leader -> leader: can not scan member node
leader -> backend: send aggregate data without dead battery node
alt COUNT > Threshold
    backend -> backend: unregister dead battery node from group
    backend -> leader: notify new group
end
end
@enduml