@startuml
title On Sensor Activation
autonumber
'Entity
participant Sensor1 as sensor1 #e1f7d5
participant Sensor2 as sensor2 #ffbdbd
participant Server as backend <<LoRaWAN Backend>> #c9c9ff
'Sequence
sensor1 -> backend: join lorawan network
sensor2 -> backend: join lorawan network
backend -> backend: elect search node randomly

backend -> sensor2: notify you are advertise node
note left #ffbdbd
Advertise Node
end note
sensor2 -> sensor2: enter deep sleep on LoRaWAN
sensor2 -> sensor2: advertise on BLE
backend -> sensor1: notify you are seed node (scan node)
note left #e1f7d5
Seed Node
end note
sensor1 -> sensor1: scan advertise data on BLE
sensor1 -> backend: send surrounding sensor node information
'backend processing
backend -> backend: collect data from seed node
backend -> backend: eliminate duplicate node by RSSi (lower RSSi)
backend -> backend: crate group
backend -> sensor1: notify you are leader node
note left #e1f7d5
Leader Node
end note
backend -> sensor2: notify you are member node and leader node UUID
note left #ffbdbd
Member Node
end note
@enduml